esphome:
  name: esp8266-iot5-dir2
  friendly_name: ESP8266_IoT5_D1R2
  platform: ESP8266
  board: d1_mini


# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "HaSRUShS0FkXy6/nyd+tg68Rl+hJzNq2PMUD/fnE9NU="

ota:
  password: "35357c0a8685db0600ada6aaaef49d09"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp8266-Iot5 Fallback Hotspot"
    password: "YSidKKcP5F3q"

captive_portal:

binary_sensor:
  - platform: gpio
    pin: GPIO5
    name: "sensor PIR"
    device_class: motion

number:
  - platform: template
    name: Servo Control
    min_value: -100
    max_value: 100
    step: 1
    optimistic: true
    set_action:
      then:
        - servo.write:
            id: my_servo
            level: !lambda 'return x / 100.0;'


servo:
  - id: my_servo
    output: pwm_output

# Example output platform
# On ESP32, use ledc output
output:
  - platform: esp8266_pwm
    id: pwm_output
    pin: D6
    frequency: 50 Hz
