esphome:
  name: esp8266
  friendly_name: ESP8266

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "EgCR9x4D6ALSWY68pNJjaQV013EaX0SJV1cTRPyLAXs="

ota:
  password: "22179b796ae855199f60c946f8b0513b"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp8266 Fallback Hotspot"
    password: "bMc8E5ZKyt5f"

captive_portal:
