alias: apagar ventilador
description: ""
trigger:
  - platform: numeric_state
    entity_id: sensor.esp32_iot5_temperatura
    below: 19.9
condition: []
action:
  - service: switch.turn_off
    data: {}
    target:
      area_id: jorjan
      device_id: 39d83645657ba9d0d7dd28a9d786c4b7
      entity_id: switch.esp32_iot5_rele_losjj
mode: single
