
alias: apagar luz
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.esp32_iot5_boton
    from: "on"
    to: "off"
condition: []
action:
  - service: light.turn_off
    data: {}
    target:
      area_id: jorjan
      device_id: 39d83645657ba9d0d7dd28a9d786c4b7
      entity_id: light.esp32_iot5_led_losjj
mode: single
